spring:
  main:
    web-application-type: reactive
  redis:
    host: localhost
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        # -----------------------------------------system-----------------------------------------
        - id: mall-sys-app-system
          uri: lb://mall-sys-app-system
          predicates:
            - Path=/sys/system/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 10
        # -----------------------------------------goods-----------------------------------------
        - id: mall-sys-app-goods
          uri: lb://mall-sys-app-goods
          predicates:
            - Path=/sys/goods/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 10
        # -----------------------------------------member-----------------------------------------
        - id: mall-sys-app-member
          uri: lb://mall-sys-app-member
          predicates:
            - Path=/sys/member/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 10
# --------------------------------------------------日志--------------------------------------------------
logging:
  config: classpath:log/log4j2-dev.xml