spring:
  redis:
    host: localhost

# 登录失败限制
security:
  loginFailTimeLimit: 10 # 次数
  loginFailAfterTime: 10 # 时间（分钟）

# 日志
logging:
  config: classpath:log/log4j2-dev.xml

# 密钥配置
encrypt:
  key-store:
    alias: ajin-mall
    location: classpath:key/private.key
    password: ajin-mall
    secret: ajin-mall