spring:
  redis:
    host: localhost
  datasource:
    url: mpw:+g7Vb573ZiEUoetgRFRSAy73He7ItRZVxHg65DbKCyvDEPYKh+VV709lzMZJyE/9e2V9rTNPeQzfcDOtH9SYB1af2FUwU20Dk/ca1s8GLpxFnI1vf89EJ/M6pzigGzP8ZAQ82zBTsMf2zNNlUF3ECHvbQ8P8BKEgfMvcgldkOHq9pAX79E1Azaz5j5LCm/O4EHkPV8tmBfd6Z+EcgBFOA992mqDMjRUIoemyd/QlOYDg3bYNt3rDzsf5yhVnCney
    username: mpw:3PREIhFqY2lF8FXXIETPkA==
    password: mpw:6/a0fTR89mwEPe+jVDfKkQ==
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
# mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
# 日志
logging:
  config: classpath:log/log4j2-test.xml
# swagger文档
springfox:
  documentation:
    auto-startup: true
    enabled: true
swagger:
  title: ${spring.application.name}